/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type ShowPetByIdRequest = {
    /**
     * The id of the pet to retrieve
     */
    petId: string;
};

export type ShowPetByIdResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Expected response to a valid request
     */
    pet?: components.Pet | undefined;
    /**
     * unexpected error
     */
    error?: components.ErrorT | undefined;
};

/** @internal */
export namespace ShowPetByIdRequest$ {
    export const inboundSchema: z.ZodType<ShowPetByIdRequest, z.ZodTypeDef, unknown> = z.object({
        petId: z.string(),
    });

    export type Outbound = {
        petId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ShowPetByIdRequest> = z.object({
        petId: z.string(),
    });
}

/** @internal */
export namespace ShowPetByIdResponse$ {
    export const inboundSchema: z.ZodType<ShowPetByIdResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Pet: components.Pet$.inboundSchema.optional(),
            Error: components.ErrorT$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                Pet: "pet",
                Error: "error",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Pet?: components.Pet$.Outbound | undefined;
        Error?: components.ErrorT$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ShowPetByIdResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            pet: components.Pet$.outboundSchema.optional(),
            error: components.ErrorT$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                pet: "Pet",
                error: "Error",
            });
        });
}
