/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type ErrorT = {
    code: number;
    message: string;
};

/** @internal */
export namespace ErrorT$ {
    export const inboundSchema: z.ZodType<ErrorT, z.ZodTypeDef, unknown> = z.object({
        code: z.number().int(),
        message: z.string(),
    });

    export type Outbound = {
        code: number;
        message: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ErrorT> = z.object({
        code: z.number().int(),
        message: z.string(),
    });
}
